apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecomm-db-pv-staging
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/ecomm-db-staging
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecomm-db-pvc
  namespace: ecomm-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
