apiVersion: v1
kind: Namespace
metadata:
  name: ecomm-prod
  labels:
    environment: prod
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ecomm-prod-quota
  namespace: ecomm-prod
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "8Gi"
    limits.cpu: "16"
    limits.memory: "16Gi"
