apiVersion: v1
kind: Secret
metadata:
  name: ecomm-db-secret
  namespace: ecomm-prod
type: Opaque
stringData:
  POSTGRES_DB: ecommerce
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  DB_USER: postgres
  DB_PASSWORD: password
